// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserCredential = `-- name: CreateUserCredential :one
INSERT INTO user_credentials (
    user_id,
    password_hash
)
VALUES (
    $1,
    $2
)
RETURNING
    id,
    user_id,
    password_hash,
    created_at,
    updated_at
`

type CreateUserCredentialParams struct {
	UserID       int64
	PasswordHash string
}

// Creates or stores a user's password credential.
func (q *Queries) CreateUserCredential(ctx context.Context, arg CreateUserCredentialParams) (UserCredential, error) {
	row := q.db.QueryRow(ctx, createUserCredential, arg.UserID, arg.PasswordHash)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserSession = `-- name: CreateUserSession :one
INSERT INTO user_sessions (
    user_id,
    token_hash,
    expires_at
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    user_id,
    token_hash,
    expires_at,
    created_at,
    last_seen_at,
    revoked_at
`

type CreateUserSessionParams struct {
	UserID    int64
	TokenHash string
	ExpiresAt pgtype.Timestamp
}

// Creates a new authentication session.
func (q *Queries) CreateUserSession(ctx context.Context, arg CreateUserSessionParams) (UserSession, error) {
	row := q.db.QueryRow(ctx, createUserSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const getUserCredential = `-- name: GetUserCredential :one
SELECT
    id,
    user_id,
    password_hash,
    created_at,
    updated_at
FROM user_credentials
WHERE user_id = $1
`

// Returns the password credential for a user.
func (q *Queries) GetUserCredential(ctx context.Context, userID int64) (UserCredential, error) {
	row := q.db.QueryRow(ctx, getUserCredential, userID)
	var i UserCredential
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PasswordHash,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserSessionByTokenHash = `-- name: GetUserSessionByTokenHash :one
SELECT
    id,
    user_id,
    token_hash,
    expires_at,
    created_at,
    last_seen_at,
    revoked_at
FROM user_sessions
WHERE token_hash = $1
`

// Returns a session by its token hash.
func (q *Queries) GetUserSessionByTokenHash(ctx context.Context, tokenHash string) (UserSession, error) {
	row := q.db.QueryRow(ctx, getUserSessionByTokenHash, tokenHash)
	var i UserSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastSeenAt,
		&i.RevokedAt,
	)
	return i, err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
UPDATE user_sessions
SET
    revoked_at = NOW()
WHERE user_id = $1
  AND revoked_at IS NULL
`

// Revokes all sessions belonging to a user.
func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeUserSession = `-- name: RevokeUserSession :exec
UPDATE user_sessions
SET
    revoked_at = NOW()
WHERE id = $1
  AND revoked_at IS NULL
`

// Revokes a session.
func (q *Queries) RevokeUserSession(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, revokeUserSession, id)
	return err
}

const updateUserPasswordHash = `-- name: UpdateUserPasswordHash :exec
UPDATE user_credentials
SET
    password_hash = $2,
    updated_at = NOW()
WHERE user_id = $1
`

type UpdateUserPasswordHashParams struct {
	UserID       int64
	PasswordHash string
}

// Updates an existing password hash.
func (q *Queries) UpdateUserPasswordHash(ctx context.Context, arg UpdateUserPasswordHashParams) error {
	_, err := q.db.Exec(ctx, updateUserPasswordHash, arg.UserID, arg.PasswordHash)
	return err
}

const updateUserSessionLastSeen = `-- name: UpdateUserSessionLastSeen :exec
UPDATE user_sessions
SET
    last_seen_at = NOW()
WHERE id = $1
`

// Updates the most recent session activity.
func (q *Queries) UpdateUserSessionLastSeen(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, updateUserSessionLastSeen, id)
	return err
}
