// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID        int64
	Email     string
	Username  string
	CreatedAt pgtype.Timestamp
	UpdatedAt pgtype.Timestamp
}

type UserCredential struct {
	ID           int64
	UserID       int64
	PasswordHash string
	CreatedAt    pgtype.Timestamp
	UpdatedAt    pgtype.Timestamp
}

type UserSession struct {
	ID         int64
	UserID     int64
	TokenHash  string
	ExpiresAt  pgtype.Timestamp
	CreatedAt  pgtype.Timestamp
	LastSeenAt pgtype.Timestamp
	RevokedAt  pgtype.Timestamp
}
