// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: oauth.sql

package db

import (
	"context"
)

const createOAuthIdentity = `-- name: CreateOAuthIdentity :one
INSERT INTO user_oauth_identities (
    user_id,
    provider,
    provider_subject
)
VALUES (
    $1,
    $2,
    $3
)
RETURNING
    id,
    user_id,
    provider,
    provider_subject,
    created_at,
    updated_at
`

type CreateOAuthIdentityParams struct {
	UserID          int64
	Provider        string
	ProviderSubject string
}

// Creates an OAuth identity.
func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) (UserOauthIdentity, error) {
	row := q.db.QueryRow(ctx, createOAuthIdentity, arg.UserID, arg.Provider, arg.ProviderSubject)
	var i UserOauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthIdentity = `-- name: DeleteOAuthIdentity :exec
DELETE FROM user_oauth_identities
WHERE id = $1
  AND user_id = $2
`

type DeleteOAuthIdentityParams struct {
	ID     int64
	UserID int64
}

// Deletes an OAuth identity.
func (q *Queries) DeleteOAuthIdentity(ctx context.Context, arg DeleteOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, deleteOAuthIdentity, arg.ID, arg.UserID)
	return err
}

const getOAuthIdentity = `-- name: GetOAuthIdentity :one
SELECT
    id,
    user_id,
    provider,
    provider_subject,
    created_at,
    updated_at
FROM user_oauth_identities
WHERE provider = $1
  AND provider_subject = $2
`

type GetOAuthIdentityParams struct {
	Provider        string
	ProviderSubject string
}

// Returns an OAuth identity by provider and provider subject.
func (q *Queries) GetOAuthIdentity(ctx context.Context, arg GetOAuthIdentityParams) (UserOauthIdentity, error) {
	row := q.db.QueryRow(ctx, getOAuthIdentity, arg.Provider, arg.ProviderSubject)
	var i UserOauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserOAuthIdentity = `-- name: GetUserOAuthIdentity :one
SELECT
    id,
    user_id,
    provider,
    provider_subject,
    created_at,
    updated_at
FROM user_oauth_identities
WHERE user_id = $1
  AND provider = $2
`

type GetUserOAuthIdentityParams struct {
	UserID   int64
	Provider string
}

// Returns an OAuth identity for a user and provider.
func (q *Queries) GetUserOAuthIdentity(ctx context.Context, arg GetUserOAuthIdentityParams) (UserOauthIdentity, error) {
	row := q.db.QueryRow(ctx, getUserOAuthIdentity, arg.UserID, arg.Provider)
	var i UserOauthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderSubject,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
